name: taski_todo
description: "Taski Todo é um aplicativo de gerenciamento de tarefas construído em Flutter, com suporte offline (Hive) e arquitetura MVVM"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  hive: ^2.2.3
  
  flutter_svg: ^2.0.16
  path_provider: ^2.1.5
  provider: ^6.1.2
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.2
  
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14


flutter_native_splash:
  color: "#007FFF"
  image: "assets/app/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/app/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app/icon-android.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  
  assets:
   - assets/

