name: taski_todo
description: "Taski Todo é um aplicativo de gerenciamento de tarefas construído em Flutter, com suporte offline (Hive) e arquitetura MVVM"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  hive: ^2.2.3
  
  flutter_svg: ^2.0.16
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  
  assets:
   - assets/

